"""add unique constraint to email and username columns

Revision ID: 6225d1b66834
Revises: db87371bcbad
Create Date: 2023-11-03 22:45:30.560825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6225d1b66834'
down_revision: Union[str, None] = 'db87371bcbad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['username'], schema='gold_list_method')
    op.create_unique_constraint(None, 'user', ['email'], schema='gold_list_method')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', schema='gold_list_method', type_='unique')
    op.drop_constraint(None, 'user', schema='gold_list_method', type_='unique')
    # ### end Alembic commands ###
