"""create tables gold_list_method schema

Revision ID: bac3011f197e
Revises: 
Create Date: 2023-10-25 12:12:06.303504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bac3011f197e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notebook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.Column('list_size', sa.Integer(), nullable=True),
    sa.Column('days_period', sa.Integer(), nullable=True),
    sa.Column('foreign_idiom', sa.String(length=100), nullable=True),
    sa.Column('mother_idiom', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='gold_list_method'
    )
    op.create_table('sentence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('foreign_language', sa.String(), nullable=True),
    sa.Column('mother_tongue', sa.String(), nullable=True),
    sa.Column('foreign_idiom', sa.String(), nullable=True),
    sa.Column('mother_idiom', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='gold_list_method'
    )
    op.create_table('page_section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_number', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('group', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('distillation_at', sa.Date(), nullable=True),
    sa.Column('distillated', sa.Boolean(), nullable=True),
    sa.Column('distillation_actual', sa.Date(), nullable=True),
    sa.Column('translated_sentences', sa.String(), nullable=True),
    sa.Column('memorializeds', sa.String(), nullable=True),
    sa.Column('notebook_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['gold_list_method.page_section.id'], ),
    sa.ForeignKeyConstraint(['notebook_id'], ['gold_list_method.notebook.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gold_list_method'
    )
    op.create_table('pagesection_sentence_assoc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('pagesection_id', sa.Integer(), nullable=True),
    sa.Column('sentence_id', sa.Integer(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('group', sa.String(length=2), nullable=True),
    sa.Column('memorialized', sa.Boolean(), nullable=True),
    sa.Column('distillated', sa.Boolean(), nullable=True),
    sa.Column('notebook_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pagesection_id'], ['gold_list_method.page_section.id'], ),
    sa.ForeignKeyConstraint(['sentence_id'], ['gold_list_method.sentence.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='gold_list_method'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagesection_sentence_assoc', schema='gold_list_method')
    op.drop_table('page_section', schema='gold_list_method')
    op.drop_table('sentence', schema='gold_list_method')
    op.drop_table('notebook', schema='gold_list_method')
    # ### end Alembic commands ###
