"""alter page_section table

Revision ID: f332168bdbf5
Revises: df09e5c9c6e9
Create Date: 2023-10-12 20:43:12.058654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f332168bdbf5'
down_revision: Union[str, None] = 'df09e5c9c6e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('page_section', 'group',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=2),
               existing_nullable=True,
               schema='gold_list_method')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('page_section', 'group',
               existing_type=sa.String(length=2),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True,
               schema='gold_list_method')
    # ### end Alembic commands ###
